; Taksi configuration file

[TAKSI]
Debug=0

; capture directory
; (NOTE: must end with a backslash)
CaptureDir="c:\Tmp\"

; desired frame rate of captured video
MovieFrameRateTarget=10

; Hot key mappings
; Note: you must use hex.numbers that correspond
; to Windows "virtual key" values (i.e. VK_xxx), as defined
; in winuser.h. Here are some commonly used ones:
; F1 - F12    : 0x70 - 0x7b
; NumLock     : 0x90
; ScrollLock  : 0x91
; Shift       : 0x10
; Ctrl        : 0x11
VKey_ConfigOpen=1136
VKey_HookModeToggle=1141
VKey_IndicatorToggle=628
VKey_RecordStart=118
VKey_RecordStop=123
VKey_Screenshot=1143
VKey_SmallScreenshot=1139

; ADVANCED OPTIONS
StartupHookModeSystemWide=1

; This option allows to pick one of two methods of
; handling hot-keys:
; 0 - use keyboard hook.
; 1 - use DirectInput. (requires DirectX 8.1).
KeyboardUseDirectInput=1

; Experimental option to capture full-size video.
; WARNING: MAKE SURE YOU HAVE ENOUGH DISK SPACE AND THAT YOUR GRAPHICS
; CARD IS BLAZINGLY FAST, BEFORE TURNING THIS OPTION ON.
VideoHalfSize=0
VideoCodecInfo=64,0,0,0,1,0,0,0,0,0,0,0,118,105,100,99,120,118,105,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,44,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,204,13,0,0

AudioCodecInfo=49,0,1,0,64,31,0,0,89,6,0,0,65,0,0,0,2,0,64
AudioDevice=-2
ShowIndicator=1

; CUSTOM VIDEO CAPTURE SETTINGS
; Custom frame capturing settings can overwrite general
; setting on per-process basis. The settings have the following format:
; [TAKSI_CUSTOM <id>]
; pattern = "<pattern>"
; frameRate = <rate>
; frameWeight = <weight>
;
; where <id> is either a number or a word, which uniquelly
; identifies this group of settings. <pattern> is a string that will
; be matched against the process filename; <rate> is an integer frame
; rate in FPS; and <weight> is a floating-point weight of each frame.
;
; (For example: 1.0 weight means that every frame will be
; recorded in the video, 0.4 weight means that out of each
; 5 frames 2 will be recorded, 3.0 weight means each frame will be
; duplicated 3 times in the video).
;
; You can put as many groups as you want, as long as each group
; has a unique id.
;
; Sample settings:
; (work well for me with Pro Evolution Soccer 3)
;
[TAKSI_CUSTOM Pro Evolution Soccer 3]
Pattern="pes3"
FrameRate=20
FrameWeight=0.4

